 # docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkinsserver
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-home:/home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    depends_on:
      - docker
  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    volumes:
      - /var/lib/docker
    restart: always

  sonarqube:
        image: sonarqube
        restart: unless-stopped
        container_name: sonarqube
        environment:
               - SONARQUBE_JDBC_USERNAME=sonarqube
               - SONARQUBE_JDBC_PASSWORD=sonarpass
               - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
        ports:
            - "9000:9000"
            - "9092:9092"

  db:
      image: postgres:13
      container_name: postgresql
      environment:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
          POSTGRES_DB: sonar
      volumes:
           - postgresql:/var/lib/postgresql
           - postgresql_data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    user: root
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

    
   

volumes:
  jenkins-data: {}
  jenkins-home: {}
  nexus-data: {}
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: